#Created by Kerjox095

version: '3'

services:
  apache-php:
    container_name: apache-php
    image: php:8.0.5-apache
    ports: 
      - 0.0.0.0:80:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html/
    
volumes:
  apache-php:
    name: apache-php-volume

